### ISSUE TITLE
Replace MAINTAINER with LABEL

### ISSUE THREAD

**Issue by yukiisbored** [coala/rultor-python#23]
The MAINTAINER instruction has been [deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) in favor of a more flexible solutions, LABEL.

Please, replace `MAINTAINER` with a `LABEL MAINTAINER=`.

**Comment by RaiVaibhav** [comment]
@yukiisbored @Makman2 @stellargo  Sir can you review it please
