### ISSUE TITLE
Add Travis CI badge to README.md

### ISSUE THREAD

**Issue by co-robo** [coala/rultor-python#29]
Add [![Build Status](https://travis-ci.org/coala/rultor-python.svg?branch=master)](https://travis-ci.org/coala/rultor-python)
label: difficulty/low
Opened by @aashutoshrathi at [Gitter](https://gitter.im/coala/coala?at=59fef4c3f7299e8f537460e4)

**Comment by itsrainingmani** [comment]
I added the badge to the Readme.md file. Is it ok to submit a PR?

**Comment by userzimmermann** [comment]
@tsmanikandan No, it's strictly forbidden ;P
