### ISSUE TITLE
.travis.yml: Put statement into single line

### ISSUE THREAD

**Issue by Makman2** [coala/rultor-python#32]
```
  - >
    docker run -v=$(pwd):/app --workdir=/app
    coala/base coala --ci
```
This command can be put into a single line, compacting the file a bit.

**Comment by aashutoshrathi** [comment]
This issue is resolved. @userzimmermann @Makman2

**Comment by userzimmermann** [comment]
@aashutoshrathi Yes, you were a bit faster with #30 and #31 :D

**Comment by Makman2** [comment]
Oops :)
